/*
 * Copyright 2025-2026 AxionOS
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.launcher3.settings.compose

internal const val SEARCH_PACKAGE = "com.google.android.googlequicksearchbox"
internal const val SUGGESTIONS_PACKAGE = "com.google.android.as"
internal const val KEY_SCREEN_GENERAL = "settings_screen_general"
internal const val KEY_SCREEN_HOME = "settings_screen_home"
internal const val KEY_SCREEN_ICONS = "settings_screen_icons"
internal const val KEY_SCREEN_OVERVIEW = "settings_screen_overview"
internal const val KEY_SCREEN_ALL_APPS = "settings_screen_all_apps"
internal const val KEY_SCREEN_SEARCH = "settings_screen_search"
internal const val KEY_SCREEN_NOTIFICATIONS = "settings_screen_notifications"
internal const val KEY_SCREEN_PRIVACY = "settings_screen_privacy"
internal const val KEY_SCREEN_BACKUP = "settings_screen_backup"
internal const val KEY_SCREEN_ABOUT = "settings_screen_about"
internal const val KEY_WORKSPACE_LOCK = "pref_workspace_lock"
internal const val KEY_WORKSPACE_ICON_SCALE = "pref_workspace_icon_scale"
internal const val KEY_WORKSPACE_LABEL_SCALE = "pref_workspace_label_scale"
internal const val KEY_WORKSPACE_WALLPAPER_SCROLLING = "pref_workspace_wallpaper_scrolling"
internal const val KEY_DISABLE_WALLPAPER_ZOOM = "pref_disable_wallpaper_zoom"
internal const val KEY_WORKSPACE_SHOW_TOP_SHADOW = "pref_workspace_show_top_shadow"
internal const val KEY_LAUNCHER_BLUR_ENABLED = "pulse_launcher_blur_enabled"
internal const val KEY_LAUNCHER_BLUR_RADIUS_PCT = "pulse_launcher_blur_radius_pct"
internal const val KEY_WORKSPACE_ROUNDED_WIDGETS = "pref_workspace_rounded_widgets"
internal const val KEY_WORKSPACE_ALLOW_WIDGET_OVERLAP = "pref_workspace_allow_widget_overlap"
internal const val KEY_WORKSPACE_FORCE_WIDGET_RESIZE = "pref_workspace_force_widget_resize"
internal const val KEY_WORKSPACE_WIDGET_UNLIMITED_SIZE = "pref_workspace_widget_unlimited_size"
internal const val KEY_WORKSPACE_DOUBLE_TAP_ACTION = "pref_workspace_double_tap_action"
internal const val KEY_ICON_PACK_PACKAGE = "pref_icon_pack_package"
internal const val KEY_THEMED_ICON_PACK = "themed_icon_pack"
internal const val KEY_THEMED_ICONS = "themed_icons"
internal const val KEY_THEMED_ICON_SCALE = "themed_icon_scale"
internal const val KEY_THEMED_ICON_BACKGROUND_COLOR = "themed_icon_background_color"
internal const val KEY_THEMED_ICON_BACKGROUND_COLOR_SOURCE = "themed_icon_background_color_source"
internal const val KEY_THEMED_ICON_FOREGROUND_COLOR = "themed_icon_foreground_color"
internal const val KEY_THEMED_ICON_FOREGROUND_COLOR_SOURCE = "themed_icon_foreground_color_source"
internal const val KEY_THEMED_ICON_COLOR_PRESET = "themed_icon_color_preset"
internal const val KEY_ICON_OVERRIDES = "launcher_icon_overrides"
internal const val KEY_HOTSEAT_SEARCH_BAR = "pref_hotseat_search_bar"
internal const val KEY_HOTSEAT_SEARCH_PROVIDER = "pref_hotseat_search_provider"
internal const val KEY_SLEEP_GESTURE = "pref_sleep_gesture"
internal const val KEY_RECENTS_SHOW_LOCK_BUTTON = "pref_recents_show_lock_button"
internal const val KEY_RECENTS_SHOW_FREEFORM_BUTTON = "pref_recents_show_freeform_button"
internal const val KEY_RECENTS_OVERVIEW_SCRIM_OPACITY = "pulse_recents_overview_scrim_opacity"
internal const val KEY_ADD_ICON_TO_HOME = "pref_add_icon_to_home"
internal const val KEY_ALLOW_ROTATION = "pref_allowRotation"
internal const val KEY_DESKTOP_LABELS = "pref_desktop_show_labels"
internal const val KEY_MINUS_ONE = "pref_enable_minus_one"
internal const val KEY_SUGGESTIONS = "pref_suggestions"
internal const val KEY_NOTIFICATION_DOTS = "pref_icon_badging"
internal const val KEY_TRUST_APPS = "pref_trust_apps"
internal const val KEY_ALL_APPS_SEARCH_SETTINGS = "pref_all_apps_search_settings"
internal const val KEY_ALL_APPS_DRAWER_SETTINGS = "pref_all_apps_drawer_settings"
internal const val KEY_ALL_APPS_FOLDER_SETTINGS = "pref_all_apps_folder_settings"
internal const val KEY_ALL_APPS_DRAWER_OPTIONS = "settings_screen_all_apps_drawer_options"
internal const val KEY_ALL_APPS_SMART_DRAWER_FOLDERS = "pref_all_apps_smart_drawer_folders"
internal const val KEY_ALL_APPS_SEARCH_RESULTS = "settings_screen_all_apps_search_results"
internal const val KEY_DRAWER_OPEN_KEYBOARD = "pref_drawer_open_keyboard"
internal const val KEY_ALLAPPS_THEMED_ICONS = "pref_allapps_themed_icons"
internal const val KEY_DRAWER_LABELS = "pref_drawer_show_labels"
internal const val KEY_ALL_APPS_BG_OPACITY = "pref_all_apps_bg_opacity"
internal const val KEY_ALL_APPS_DRAWER_COLUMNS = "pref_all_apps_drawer_columns"
internal const val KEY_ALL_APPS_DRAWER_ICON_SCALE = "pref_all_apps_drawer_icon_scale"
internal const val KEY_ALL_APPS_DRAWER_LABEL_SCALE = "pref_all_apps_drawer_label_scale"
internal const val KEY_ALL_APPS_DRAWER_ROW_SCALE = "pref_all_apps_drawer_row_scale"
internal const val KEY_ALL_APPS_DRAWER_SIDE_PADDING_SCALE =
    "pref_all_apps_drawer_side_padding_scale"
internal const val KEY_ALL_APPS_REMEMBER_POSITION = "pref_all_apps_remember_position"
internal const val KEY_ALL_APPS_SHOW_SCROLLBAR = "pref_all_apps_show_scrollbar"
internal const val KEY_ALL_APPS_HAPTIC_FEEDBACK = "pref_all_apps_haptic_feedback"
internal const val KEY_ALL_APPS_DRAWER_LAYOUT_MODE = "pref_app_drawer_layout_mode"
internal const val KEY_ALL_APPS_PREDICTIONS = "pref_all_apps_predictions"
internal const val KEY_SEARCH_RESULT_APPS = "pref_all_apps_search_result_apps"
internal const val KEY_SEARCH_RESULT_APP_ACTIONS = "pref_all_apps_search_result_app_actions"
internal const val KEY_SEARCH_RESULT_QUICK_ANSWERS = "pref_all_apps_search_result_quick_answers"
internal const val KEY_SEARCH_RESULT_SETTINGS = "pref_all_apps_search_result_settings"
internal const val KEY_SEARCH_RESULT_CONTACTS = "pref_all_apps_search_result_contacts"
internal const val KEY_SEARCH_RESULT_IMAGES = "pref_all_apps_search_result_images"
internal const val KEY_SEARCH_RESULT_FILES = "pref_all_apps_search_result_files"
internal const val KEY_SEARCH_RESULT_CALENDAR = "pref_all_apps_search_result_calendar"
internal const val KEY_SEARCH_RESULT_WEB = "pref_all_apps_search_result_web"
internal const val KEY_SEARCH_RESULT_IN_APPS = "pref_all_apps_search_result_in_apps"
internal const val KEY_SEARCH_RESULT_MEDIA = "pref_all_apps_search_result_media"
internal const val KEY_SEARCH_FUZZY_APPS = "pref_all_apps_search_fuzzy_apps"
internal const val KEY_SEARCH_MAX_APPS = "pref_all_apps_search_max_apps"
internal const val KEY_SEARCH_MAX_APP_ACTIONS = "pref_all_apps_search_max_app_actions"
internal const val KEY_SEARCH_MAX_EXTERNAL_RESULTS = "pref_all_apps_search_max_external_results"
internal const val KEY_SEARCH_WEB_DELAY_MS = "pref_all_apps_search_web_delay_ms"
internal const val KEY_SEARCH_HISTORY_CLEAR = "pref_all_apps_search_history_clear"
internal const val KEY_SEARCH_PERMISSION_CONTACTS = "pref_all_apps_search_permission_contacts"
internal const val KEY_SEARCH_PERMISSION_STORAGE = "pref_all_apps_search_permission_storage"
internal const val KEY_SEARCH_PERMISSION_CALENDAR = "pref_all_apps_search_permission_calendar"
internal const val KEY_BACKUP_EXPORT = "pref_launcher_backup_export"
internal const val KEY_BACKUP_IMPORT = "pref_launcher_backup_import"
internal const val LAUNCHER_LAYOUT_FILE_NAME = "launcher_layout.xml"
internal const val CONTENT_SUGGESTIONS_ACTION =
    "android.settings.ACTION_CONTENT_SUGGESTIONS_SETTINGS"
internal const val EXTRA_SHOW_FRAGMENT_ARGS = ":settings:show_fragment_args"
internal const val NOTIFICATION_BADGING_KEY = "notification_badging"
internal const val NOTIFICATION_ENABLED_LISTENERS = "enabled_notification_listeners"
internal const val REQUEST_SEARCH_CONTACTS_PERMISSION = 1
internal const val REQUEST_SEARCH_STORAGE_PERMISSION = 2
internal const val REQUEST_SEARCH_CALENDAR_PERMISSION = 3
internal const val AXION_LAUNCHER_SOURCE_URL =
    "https://github.com/AxionAOSP/android_packages_apps_Launcher3"
internal const val AXION_TRANSLATE_URL = "https://crowdin.com/project/axionos"
internal const val AXION_DONATE_URL = "https://buymeacoffee.com/rmp22"
